# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_equations.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(978, 589)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        Form.setFont(font)
        Form.setToolTip(_fromUtf8(""))
        self.groupEquationEditor = QtGui.QGroupBox(Form)
        self.groupEquationEditor.setGeometry(QtCore.QRect(10, 110, 951, 321))
        self.groupEquationEditor.setObjectName(_fromUtf8("groupEquationEditor"))
        self.lineNewVariable = QtGui.QLineEdit(self.groupEquationEditor)
        self.lineNewVariable.setGeometry(QtCore.QRect(11, 50, 181, 27))
        self.lineNewVariable.setObjectName(_fromUtf8("lineNewVariable"))
        self.layoutWidget = QtGui.QWidget(self.groupEquationEditor)
        self.layoutWidget.setGeometry(QtCore.QRect(430, 10, 178, 30))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushAccept = QtGui.QPushButton(self.layoutWidget)
        self.pushAccept.setMinimumSize(QtCore.QSize(85, 0))
        self.pushAccept.setMaximumSize(QtCore.QSize(85, 16777215))
        self.pushAccept.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 255);\n"
"color :rgb(255, 255, 255)"))
        self.pushAccept.setObjectName(_fromUtf8("pushAccept"))
        self.horizontalLayout_2.addWidget(self.pushAccept)
        self.pushDeleteEquation = QtGui.QPushButton(self.layoutWidget)
        self.pushDeleteEquation.setMinimumSize(QtCore.QSize(85, 0))
        self.pushDeleteEquation.setMaximumSize(QtCore.QSize(85, 16777215))
        self.pushDeleteEquation.setStyleSheet(_fromUtf8("background-color: rgb(255, 17, 0);\n"
"color:rgb(255, 255, 255)"))
        self.pushDeleteEquation.setObjectName(_fromUtf8("pushDeleteEquation"))
        self.horizontalLayout_2.addWidget(self.pushDeleteEquation)
        self.layoutWidget1 = QtGui.QWidget(self.groupEquationEditor)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 90, 941, 30))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.lineExpression = QtGui.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        self.lineExpression.setFont(font)
        self.lineExpression.setObjectName(_fromUtf8("lineExpression"))
        self.horizontalLayout_5.addWidget(self.lineExpression)
        self.labelQuestion = QtGui.QLabel(Form)
        self.labelQuestion.setGeometry(QtCore.QRect(1080, -470, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelQuestion.setFont(font)
        self.labelQuestion.setAutoFillBackground(False)
        self.labelQuestion.setStyleSheet(_fromUtf8("background-color: rgb(255, 17, 0);"))
        self.labelQuestion.setAlignment(QtCore.Qt.AlignCenter)
        self.labelQuestion.setObjectName(_fromUtf8("labelQuestion"))
        self.labelNetwork = QtGui.QLabel(Form)
        self.labelNetwork.setGeometry(QtCore.QRect(20, 10, 741, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelNetwork.setFont(font)
        self.labelNetwork.setObjectName(_fromUtf8("labelNetwork"))
        self.layoutWidget2 = QtGui.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 450, 941, 42))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setStyleSheet(_fromUtf8("background-color: rgb(148, 148, 56);\n"
"color :rgb(255, 255, 255)"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.pushPickVariables = QtGui.QPushButton(self.layoutWidget2)
        self.pushPickVariables.setObjectName(_fromUtf8("pushPickVariables"))
        self.horizontalLayout_3.addWidget(self.pushPickVariables)
        self.pushPickIndices = QtGui.QPushButton(self.layoutWidget2)
        self.pushPickIndices.setObjectName(_fromUtf8("pushPickIndices"))
        self.horizontalLayout_3.addWidget(self.pushPickIndices)
        self.pushPickOperations = QtGui.QPushButton(self.layoutWidget2)
        self.pushPickOperations.setObjectName(_fromUtf8("pushPickOperations"))
        self.horizontalLayout_3.addWidget(self.pushPickOperations)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushCancel = QtGui.QPushButton(self.layoutWidget2)
        self.pushCancel.setObjectName(_fromUtf8("pushCancel"))
        self.horizontalLayout.addWidget(self.pushCancel)
        self.pushResetInterface = QtGui.QPushButton(self.layoutWidget2)
        self.pushResetInterface.setObjectName(_fromUtf8("pushResetInterface"))
        self.horizontalLayout.addWidget(self.pushResetInterface)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.lineDocumentation = QtGui.QLineEdit(Form)
        self.lineDocumentation.setGeometry(QtCore.QRect(20, 390, 941, 27))
        self.lineDocumentation.setText(_fromUtf8(""))
        self.lineDocumentation.setObjectName(_fromUtf8("lineDocumentation"))
        self.textBrowser = QtGui.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(20, 250, 941, 131))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.layoutWidget.raise_()
        self.labelNetwork.raise_()
        self.groupEquationEditor.raise_()
        self.labelQuestion.raise_()
        self.lineDocumentation.raise_()
        self.textBrowser.raise_()

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.lineNewVariable, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.lineExpression.show)
        QtCore.QObject.connect(self.lineNewVariable, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.lineExpression.setFocus)
        QtCore.QObject.connect(self.lineExpression, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.lineDocumentation.setFocus)
        QtCore.QObject.connect(self.lineDocumentation, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.lineExpression.setFocus)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupEquationEditor.setToolTip(_translate("Form", "Equation editor", None))
        self.groupEquationEditor.setTitle(_translate("Form", "Equation Editor:  Variable := Expression", None))
        self.lineNewVariable.setToolTip(_translate("Form", "variable field", None))
        self.pushAccept.setToolTip(_translate("Form", "puts things in place and closes equation editor", None))
        self.pushAccept.setText(_translate("Form", "accept", None))
        self.pushDeleteEquation.setText(_translate("Form", "delete", None))
        self.label.setText(_translate("Form", ":=", None))
        self.lineExpression.setToolTip(_translate("Form", "equation editor field -- press return when finished", None))
        self.labelQuestion.setToolTip(_translate("Form", "Variable equation editor\n"
"Generates new variables and equations\n"
"Resulting bipartite graph (variable|equation) must be complete before ontology can be used\n"
"predefined variables: t, dt, t0", None))
        self.labelQuestion.setText(_translate("Form", "?", None))
        self.labelNetwork.setText(_translate("Form", "TextLabel", None))
        self.label_2.setToolTip(_translate("Form", "Pick tables", None))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">  pick tables  </span></p></body></html>", None))
        self.pushPickVariables.setToolTip(_translate("Form", "pick variable table", None))
        self.pushPickVariables.setText(_translate("Form", "variables", None))
        self.pushPickIndices.setToolTip(_translate("Form", "pick index table", None))
        self.pushPickIndices.setText(_translate("Form", "indices", None))
        self.pushPickOperations.setToolTip(_translate("Form", "pick operations", None))
        self.pushPickOperations.setText(_translate("Form", "operations", None))
        self.pushCancel.setToolTip(_translate("Form", "reset closes equation editor clears alias table", None))
        self.pushCancel.setText(_translate("Form", "cancel", None))
        self.pushResetInterface.setToolTip(_translate("Form", "reset closes equation editor clears alias table", None))
        self.pushResetInterface.setText(_translate("Form", "reset", None))
        self.lineDocumentation.setPlaceholderText(_translate("Form", "describe equation", None))

