# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ontology_design.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OntologyDesigner(object):
    def setupUi(self, OntologyDesigner):
        OntologyDesigner.setObjectName(_fromUtf8("OntologyDesigner"))
        OntologyDesigner.resize(416, 904)
        self.groupVariables = QtGui.QGroupBox(OntologyDesigner)
        self.groupVariables.setGeometry(QtCore.QRect(20, 260, 381, 541))
        self.groupVariables.setObjectName(_fromUtf8("groupVariables"))
        self.tabWidget = QtGui.QTabWidget(self.groupVariables)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 351, 411))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_networks = QtGui.QWidget()
        self.tab_networks.setObjectName(_fromUtf8("tab_networks"))
        self.treeWidget = QtGui.QTreeWidget(self.tab_networks)
        self.treeWidget.setGeometry(QtCore.QRect(10, 20, 311, 261))
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.treeWidget.header().setVisible(False)
        self.groupEdit = QtGui.QGroupBox(self.tab_networks)
        self.groupEdit.setGeometry(QtCore.QRect(10, 290, 311, 81))
        self.groupEdit.setObjectName(_fromUtf8("groupEdit"))
        self.groupBoxComponents = QtGui.QGroupBox(self.groupEdit)
        self.groupBoxComponents.setGeometry(QtCore.QRect(10, 20, 281, 61))
        self.groupBoxComponents.setObjectName(_fromUtf8("groupBoxComponents"))
        self.radioArc = QtGui.QRadioButton(self.groupBoxComponents)
        self.radioArc.setGeometry(QtCore.QRect(210, 30, 61, 22))
        self.radioArc.setObjectName(_fromUtf8("radioArc"))
        self.radioNode = QtGui.QRadioButton(self.groupBoxComponents)
        self.radioNode.setGeometry(QtCore.QRect(130, 30, 71, 22))
        self.radioNode.setObjectName(_fromUtf8("radioNode"))
        self.radioGraph = QtGui.QRadioButton(self.groupBoxComponents)
        self.radioGraph.setGeometry(QtCore.QRect(30, 30, 71, 22))
        self.radioGraph.setObjectName(_fromUtf8("radioGraph"))
        self.tabWidget.addTab(self.tab_networks, _fromUtf8(""))
        self.tab_intranets = QtGui.QWidget()
        self.tab_intranets.setObjectName(_fromUtf8("tab_intranets"))
        self.combo_IntraConnectionNetwork = QtGui.QComboBox(self.tab_intranets)
        self.combo_IntraConnectionNetwork.setGeometry(QtCore.QRect(30, 50, 289, 27))
        self.combo_IntraConnectionNetwork.setObjectName(_fromUtf8("combo_IntraConnectionNetwork"))
        self.tabWidget.addTab(self.tab_intranets, _fromUtf8(""))
        self.tab_internets = QtGui.QWidget()
        self.tab_internets.setObjectName(_fromUtf8("tab_internets"))
        self.combo_InterConnectionNetwork = QtGui.QComboBox(self.tab_internets)
        self.combo_InterConnectionNetwork.setGeometry(QtCore.QRect(30, 50, 289, 27))
        self.combo_InterConnectionNetwork.setObjectName(_fromUtf8("combo_InterConnectionNetwork"))
        self.tabWidget.addTab(self.tab_internets, _fromUtf8(""))
        self.combo_EditVariableTypes = QtGui.QComboBox(self.groupVariables)
        self.combo_EditVariableTypes.setGeometry(QtCore.QRect(40, 470, 301, 27))
        self.combo_EditVariableTypes.setObjectName(_fromUtf8("combo_EditVariableTypes"))
        self.groupOntology = QtGui.QGroupBox(OntologyDesigner)
        self.groupOntology.setGeometry(QtCore.QRect(20, 10, 381, 131))
        self.groupOntology.setObjectName(_fromUtf8("groupOntology"))
        self.pushInfo = QtGui.QPushButton(self.groupOntology)
        self.pushInfo.setGeometry(QtCore.QRect(320, 40, 40, 40))
        self.pushInfo.setText(_fromUtf8(""))
        self.pushInfo.setObjectName(_fromUtf8("pushInfo"))
        self.pushCompile = QtGui.QPushButton(self.groupOntology)
        self.pushCompile.setGeometry(QtCore.QRect(320, 80, 40, 40))
        self.pushCompile.setText(_fromUtf8(""))
        self.pushCompile.setObjectName(_fromUtf8("pushCompile"))
        self.layoutWidget = QtGui.QWidget(self.groupOntology)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 133, 80))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioVariables = QtGui.QRadioButton(self.layoutWidget)
        self.radioVariables.setObjectName(_fromUtf8("radioVariables"))
        self.verticalLayout.addWidget(self.radioVariables)
        self.radioVariablesAliases = QtGui.QRadioButton(self.layoutWidget)
        self.radioVariablesAliases.setObjectName(_fromUtf8("radioVariablesAliases"))
        self.verticalLayout.addWidget(self.radioVariablesAliases)
        self.radioIndicesAliases = QtGui.QRadioButton(self.layoutWidget)
        self.radioIndicesAliases.setObjectName(_fromUtf8("radioIndicesAliases"))
        self.verticalLayout.addWidget(self.radioIndicesAliases)
        self.groupFiles = QtGui.QGroupBox(OntologyDesigner)
        self.groupFiles.setGeometry(QtCore.QRect(20, 160, 301, 61))
        self.groupFiles.setObjectName(_fromUtf8("groupFiles"))
        self.pushWrite = QtGui.QPushButton(self.groupFiles)
        self.pushWrite.setGeometry(QtCore.QRect(40, 20, 251, 31))
        self.pushWrite.setAutoDefault(False)
        self.pushWrite.setDefault(True)
        self.pushWrite.setObjectName(_fromUtf8("pushWrite"))
        self.msgWindow = QtGui.QTextBrowser(OntologyDesigner)
        self.msgWindow.setEnabled(False)
        self.msgWindow.setGeometry(QtCore.QRect(30, 810, 351, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.msgWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.msgWindow.setFont(font)
        self.msgWindow.setAcceptDrops(False)
        self.msgWindow.setObjectName(_fromUtf8("msgWindow"))

        self.retranslateUi(OntologyDesigner)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OntologyDesigner)

    def retranslateUi(self, OntologyDesigner):
        OntologyDesigner.setWindowTitle(_translate("OntologyDesigner", "Dialog", None))
        self.groupVariables.setTitle(_translate("OntologyDesigner", "variables & equations", None))
        self.groupEdit.setTitle(_translate("OntologyDesigner", "Edit", None))
        self.groupBoxComponents.setTitle(_translate("OntologyDesigner", "components", None))
        self.radioArc.setToolTip(_translate("OntologyDesigner", "select to edit variables", None))
        self.radioArc.setText(_translate("OntologyDesigner", "arc", None))
        self.radioNode.setToolTip(_translate("OntologyDesigner", "select to edit variables", None))
        self.radioNode.setText(_translate("OntologyDesigner", "node", None))
        self.radioGraph.setToolTip(_translate("OntologyDesigner", "select to edit variables", None))
        self.radioGraph.setText(_translate("OntologyDesigner", "graph", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_networks), _translate("OntologyDesigner", "networks", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_intranets), _translate("OntologyDesigner", "intr A nets", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_internets), _translate("OntologyDesigner", "int E rnets", None))
        self.groupOntology.setTitle(_translate("OntologyDesigner", "Ontology", None))
        self.radioVariables.setToolTip(_translate("OntologyDesigner", "select to edit variables", None))
        self.radioVariables.setText(_translate("OntologyDesigner", "variables", None))
        self.radioVariablesAliases.setToolTip(_translate("OntologyDesigner", "select to edit variable aliases", None))
        self.radioVariablesAliases.setText(_translate("OntologyDesigner", "variable aliases", None))
        self.radioIndicesAliases.setToolTip(_translate("OntologyDesigner", "select to edit index aliases", None))
        self.radioIndicesAliases.setText(_translate("OntologyDesigner", " index aliases", None))
        self.groupFiles.setTitle(_translate("OntologyDesigner", "Files", None))
        self.pushWrite.setToolTip(_translate("OntologyDesigner", "<html><head/><body><p>- compiles into all available code languages</p><p>- writes equations and variables as well as index file</p><p>- generates latex files with dot graphs</p></body></html>", None))
        self.pushWrite.setText(_translate("OntologyDesigner", "write - compile - document", None))

