# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor_typed_token.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1015, 537)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupToken = QtWidgets.QGroupBox(self.centralwidget)
        self.groupToken.setGeometry(QtCore.QRect(380, 30, 161, 131))
        self.groupToken.setObjectName("groupToken")
        self.spinNumberOfTypedTokens = QtWidgets.QSpinBox(self.groupToken)
        self.spinNumberOfTypedTokens.setGeometry(QtCore.QRect(40, 80, 61, 27))
        self.spinNumberOfTypedTokens.setMinimum(1)
        self.spinNumberOfTypedTokens.setObjectName("spinNumberOfTypedTokens")
        self.comboTokenWithTypedTokens = QtWidgets.QComboBox(self.groupToken)
        self.comboTokenWithTypedTokens.setGeometry(QtCore.QRect(40, 30, 85, 27))
        self.comboTokenWithTypedTokens.setObjectName("comboTokenWithTypedTokens")
        self.groupConversion = QtWidgets.QGroupBox(self.centralwidget)
        self.groupConversion.setGeometry(QtCore.QRect(560, 20, 431, 481))
        self.groupConversion.setObjectName("groupConversion")
        self.comboConversion = QtWidgets.QComboBox(self.groupConversion)
        self.comboConversion.setGeometry(QtCore.QRect(230, 60, 191, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboConversion.sizePolicy().hasHeightForWidth())
        self.comboConversion.setSizePolicy(sizePolicy)
        self.comboConversion.setObjectName("comboConversion")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupConversion)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 110, 191, 281))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formReactants = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formReactants.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.formReactants.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formReactants.setContentsMargins(0, 0, 0, 0)
        self.formReactants.setObjectName("formReactants")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupConversion)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(230, 110, 191, 281))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formProducts = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formProducts.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.formProducts.setContentsMargins(0, 0, 0, 0)
        self.formProducts.setObjectName("formProducts")
        self.pushNewConversion = QtWidgets.QPushButton(self.groupConversion)
        self.pushNewConversion.setGeometry(QtCore.QRect(20, 420, 99, 27))
        self.pushNewConversion.setObjectName("pushNewConversion")
        self.pushDelete = QtWidgets.QPushButton(self.groupConversion)
        self.pushDelete.setGeometry(QtCore.QRect(160, 420, 99, 27))
        self.pushDelete.setObjectName("pushDelete")
        self.spinConverstion = QtWidgets.QSpinBox(self.groupConversion)
        self.spinConverstion.setGeometry(QtCore.QRect(20, 60, 101, 27))
        self.spinConverstion.setObjectName("spinConverstion")
        self.groupStart = QtWidgets.QGroupBox(self.centralwidget)
        self.groupStart.setGeometry(QtCore.QRect(50, 40, 251, 111))
        self.groupStart.setTitle("")
        self.groupStart.setObjectName("groupStart")
        self.pushNewSystem = QtWidgets.QPushButton(self.groupStart)
        self.pushNewSystem.setGeometry(QtCore.QRect(20, 50, 99, 27))
        self.pushNewSystem.setObjectName("pushNewSystem")
        self.pushLoad = QtWidgets.QPushButton(self.groupStart)
        self.pushLoad.setGeometry(QtCore.QRect(130, 50, 99, 27))
        self.pushLoad.setObjectName("pushLoad")
        self.groupSaving = QtWidgets.QGroupBox(self.centralwidget)
        self.groupSaving.setGeometry(QtCore.QRect(60, 190, 251, 71))
        self.groupSaving.setTitle("")
        self.groupSaving.setObjectName("groupSaving")
        self.pushSaveAs = QtWidgets.QPushButton(self.groupSaving)
        self.pushSaveAs.setGeometry(QtCore.QRect(120, 20, 99, 27))
        self.pushSaveAs.setObjectName("pushSaveAs")
        self.pushSave = QtWidgets.QPushButton(self.groupSaving)
        self.pushSave.setGeometry(QtCore.QRect(10, 20, 101, 27))
        self.pushSave.setObjectName("pushSave")
        self.message_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.message_box.setGeometry(QtCore.QRect(50, 310, 491, 161))
        self.message_box.setObjectName("message_box")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupToken.setTitle(_translate("MainWindow", "token"))
        self.groupConversion.setTitle(_translate("MainWindow", "conversion"))
        self.pushNewConversion.setText(_translate("MainWindow", "new"))
        self.pushDelete.setText(_translate("MainWindow", "delete"))
        self.pushNewSystem.setText(_translate("MainWindow", "new"))
        self.pushLoad.setText(_translate("MainWindow", "load"))
        self.pushSaveAs.setText(_translate("MainWindow", "save as"))
        self.pushSave.setText(_translate("MainWindow", "save"))
