# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_constrain_behaviour.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 632)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollAreaEquations = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaEquations.setWidgetResizable(True)
        self.scrollAreaEquations.setObjectName("scrollAreaEquations")
        self.scrollAreaWidgetContentsEquations = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsEquations.setGeometry(QtCore.QRect(0, 0, 422, 334))
        self.scrollAreaWidgetContentsEquations.setObjectName("scrollAreaWidgetContentsEquations")
        self.scrollAreaEquations.setWidget(self.scrollAreaWidgetContentsEquations)
        self.gridLayout.addWidget(self.scrollAreaEquations, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 250))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 231, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonBaseGraph = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonBaseGraph.setObjectName("radioButtonBaseGraph")
        self.verticalLayout.addWidget(self.radioButtonBaseGraph)
        self.radioButtonDuplicates = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonDuplicates.setObjectName("radioButtonDuplicates")
        self.verticalLayout.addWidget(self.radioButtonDuplicates)
        self.radioButtonConstrain = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonConstrain.setObjectName("radioButtonConstrain")
        self.verticalLayout.addWidget(self.radioButtonConstrain)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 231, 71))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonInformation = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButtonInformation.setText("")
        self.pushButtonInformation.setObjectName("pushButtonInformation")
        self.horizontalLayout_2.addWidget(self.pushButtonInformation)
        self.pushButtonCancle = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButtonCancle.setText("")
        self.pushButtonCancle.setObjectName("pushButtonCancle")
        self.horizontalLayout_2.addWidget(self.pushButtonCancle)
        self.pushButtonSave = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButtonSave.setText("")
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_2.addWidget(self.pushButtonSave)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.scrollAreaEntities = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaEntities.setWidgetResizable(True)
        self.scrollAreaEntities.setObjectName("scrollAreaEntities")
        self.scrollAreaWidgetContentsEntities = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsEntities.setGeometry(QtCore.QRect(0, 0, 253, 334))
        self.scrollAreaWidgetContentsEntities.setObjectName("scrollAreaWidgetContentsEntities")
        self.scrollAreaEntities.setWidget(self.scrollAreaWidgetContentsEntities)
        self.gridLayout.addWidget(self.scrollAreaEntities, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.labelSource = QtWidgets.QLabel(self.centralwidget)
        self.labelSource.setObjectName("labelSource")
        self.verticalLayout_2.addWidget(self.labelSource)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 30)
        self.gridLayout.setColumnStretch(1, 50)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "controls"))
        self.radioButtonBaseGraph.setText(_translate("MainWindow", "base graph"))
        self.radioButtonDuplicates.setText(_translate("MainWindow", "duplicates"))
        self.radioButtonConstrain.setText(_translate("MainWindow", "constrain"))
        self.labelSource.setText(_translate("MainWindow", "TextLabel"))
