# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor_foundation_ontology_gui.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(856, 817)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(100, 0))
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks|QtGui.QMainWindow.ForceTabbedDocks|QtGui.QMainWindow.VerticalTabs)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBoxNetwork = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxNetwork.setGeometry(QtCore.QRect(320, 30, 120, 161))
        self.groupBoxNetwork.setObjectName(_fromUtf8("groupBoxNetwork"))
        self.layoutWidget = QtGui.QWidget(self.groupBoxNetwork)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 69, 66))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.radioButtonIntra = QtGui.QRadioButton(self.layoutWidget)
        self.radioButtonIntra.setObjectName(_fromUtf8("radioButtonIntra"))
        self.verticalLayout_3.addWidget(self.radioButtonIntra)
        self.radioButtonInter = QtGui.QRadioButton(self.layoutWidget)
        self.radioButtonInter.setObjectName(_fromUtf8("radioButtonInter"))
        self.verticalLayout_3.addWidget(self.radioButtonInter)
        self.layoutWidget1 = QtGui.QWidget(self.groupBoxNetwork)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 90, 106, 66))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushAddChild = QtGui.QPushButton(self.layoutWidget1)
        self.pushAddChild.setObjectName(_fromUtf8("pushAddChild"))
        self.verticalLayout_4.addWidget(self.pushAddChild)
        self.pushRemoveChild = QtGui.QPushButton(self.layoutWidget1)
        self.pushRemoveChild.setObjectName(_fromUtf8("pushRemoveChild"))
        self.verticalLayout_4.addWidget(self.pushRemoveChild)
        self.groupBoxFile = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxFile.setGeometry(QtCore.QRect(480, 30, 261, 80))
        self.groupBoxFile.setObjectName(_fromUtf8("groupBoxFile"))
        self.pushSave = QtGui.QPushButton(self.groupBoxFile)
        self.pushSave.setGeometry(QtCore.QRect(10, 30, 40, 40))
        self.pushSave.setText(_fromUtf8(""))
        self.pushSave.setObjectName(_fromUtf8("pushSave"))
        self.pushInfo = QtGui.QPushButton(self.groupBoxFile)
        self.pushInfo.setGeometry(QtCore.QRect(60, 30, 40, 40))
        self.pushInfo.setText(_fromUtf8(""))
        self.pushInfo.setObjectName(_fromUtf8("pushInfo"))
        self.pushGraph = QtGui.QPushButton(self.groupBoxFile)
        self.pushGraph.setGeometry(QtCore.QRect(110, 30, 40, 40))
        self.pushGraph.setText(_fromUtf8(""))
        self.pushGraph.setObjectName(_fromUtf8("pushGraph"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(40, 290, 781, 361))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_structure = QtGui.QWidget()
        self.tab_structure.setObjectName(_fromUtf8("tab_structure"))
        self.groupBoxStructureComponents = QtGui.QGroupBox(self.tab_structure)
        self.groupBoxStructureComponents.setGeometry(QtCore.QRect(20, 30, 91, 211))
        self.groupBoxStructureComponents.setObjectName(_fromUtf8("groupBoxStructureComponents"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBoxStructureComponents)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 74, 101))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButtonStructureNode = QtGui.QRadioButton(self.layoutWidget2)
        self.radioButtonStructureNode.setObjectName(_fromUtf8("radioButtonStructureNode"))
        self.verticalLayout.addWidget(self.radioButtonStructureNode)
        self.radioButtonStructureArc = QtGui.QRadioButton(self.layoutWidget2)
        self.radioButtonStructureArc.setObjectName(_fromUtf8("radioButtonStructureArc"))
        self.verticalLayout.addWidget(self.radioButtonStructureArc)
        self.radioButtonStructureToken = QtGui.QRadioButton(self.layoutWidget2)
        self.radioButtonStructureToken.setObjectName(_fromUtf8("radioButtonStructureToken"))
        self.verticalLayout.addWidget(self.radioButtonStructureToken)
        self.widgetToken = QtGui.QWidget(self.tab_structure)
        self.widgetToken.setGeometry(QtCore.QRect(120, 10, 251, 301))
        self.widgetToken.setObjectName(_fromUtf8("widgetToken"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.widgetToken)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 231, 191))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayoutToken = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayoutToken.setMargin(0)
        self.horizontalLayoutToken.setObjectName(_fromUtf8("horizontalLayoutToken"))
        self.listViewStructure = QtGui.QListWidget(self.tab_structure)
        self.listViewStructure.setGeometry(QtCore.QRect(380, 60, 191, 192))
        self.listViewStructure.setObjectName(_fromUtf8("listViewStructure"))
        self.listViewStructureExtension = QtGui.QListWidget(self.tab_structure)
        self.listViewStructureExtension.setGeometry(QtCore.QRect(580, 60, 191, 192))
        self.listViewStructureExtension.setObjectName(_fromUtf8("listViewStructureExtension"))
        self.layoutWidget3 = QtGui.QWidget(self.tab_structure)
        self.layoutWidget3.setGeometry(QtCore.QRect(380, 260, 120, 41))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushNewStructureElement = QtGui.QPushButton(self.layoutWidget3)
        self.pushNewStructureElement.setText(_fromUtf8(""))
        self.pushNewStructureElement.setObjectName(_fromUtf8("pushNewStructureElement"))
        self.horizontalLayout.addWidget(self.pushNewStructureElement)
        self.pushDeleteStructureElement = QtGui.QPushButton(self.layoutWidget3)
        self.pushDeleteStructureElement.setText(_fromUtf8(""))
        self.pushDeleteStructureElement.setObjectName(_fromUtf8("pushDeleteStructureElement"))
        self.horizontalLayout.addWidget(self.pushDeleteStructureElement)
        self.layoutWidget4 = QtGui.QWidget(self.tab_structure)
        self.layoutWidget4.setGeometry(QtCore.QRect(580, 260, 120, 41))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushNewStructureElementExtension = QtGui.QPushButton(self.layoutWidget4)
        self.pushNewStructureElementExtension.setText(_fromUtf8(""))
        self.pushNewStructureElementExtension.setObjectName(_fromUtf8("pushNewStructureElementExtension"))
        self.horizontalLayout_2.addWidget(self.pushNewStructureElementExtension)
        self.pushDeleteStructureElementExtension = QtGui.QPushButton(self.layoutWidget4)
        self.pushDeleteStructureElementExtension.setText(_fromUtf8(""))
        self.pushDeleteStructureElementExtension.setObjectName(_fromUtf8("pushDeleteStructureElementExtension"))
        self.horizontalLayout_2.addWidget(self.pushDeleteStructureElementExtension)
        self.labelStructure = QtGui.QLabel(self.tab_structure)
        self.labelStructure.setGeometry(QtCore.QRect(380, 30, 161, 17))
        self.labelStructure.setObjectName(_fromUtf8("labelStructure"))
        self.labelStructureExtension = QtGui.QLabel(self.tab_structure)
        self.labelStructureExtension.setGeometry(QtCore.QRect(580, 30, 181, 17))
        self.labelStructureExtension.setObjectName(_fromUtf8("labelStructureExtension"))
        self.tabWidget.addTab(self.tab_structure, _fromUtf8(""))
        self.tab_behaviour = QtGui.QWidget()
        self.tab_behaviour.setObjectName(_fromUtf8("tab_behaviour"))
        self.layoutWidget5 = QtGui.QWidget(self.tab_behaviour)
        self.layoutWidget5.setGeometry(QtCore.QRect(150, 260, 120, 41))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushNewBehaviourElement = QtGui.QPushButton(self.layoutWidget5)
        self.pushNewBehaviourElement.setText(_fromUtf8(""))
        self.pushNewBehaviourElement.setObjectName(_fromUtf8("pushNewBehaviourElement"))
        self.horizontalLayout_3.addWidget(self.pushNewBehaviourElement)
        self.pushDeleteBehaviourElement = QtGui.QPushButton(self.layoutWidget5)
        self.pushDeleteBehaviourElement.setText(_fromUtf8(""))
        self.pushDeleteBehaviourElement.setObjectName(_fromUtf8("pushDeleteBehaviourElement"))
        self.horizontalLayout_3.addWidget(self.pushDeleteBehaviourElement)
        self.groupBoxBehaviourComponents = QtGui.QGroupBox(self.tab_behaviour)
        self.groupBoxBehaviourComponents.setGeometry(QtCore.QRect(40, 40, 91, 211))
        self.groupBoxBehaviourComponents.setObjectName(_fromUtf8("groupBoxBehaviourComponents"))
        self.layoutWidget6 = QtGui.QWidget(self.groupBoxBehaviourComponents)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 20, 75, 101))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButtonBehaviourGraph = QtGui.QRadioButton(self.layoutWidget6)
        self.radioButtonBehaviourGraph.setObjectName(_fromUtf8("radioButtonBehaviourGraph"))
        self.verticalLayout_2.addWidget(self.radioButtonBehaviourGraph)
        self.radioButtonBehaviourNode = QtGui.QRadioButton(self.layoutWidget6)
        self.radioButtonBehaviourNode.setObjectName(_fromUtf8("radioButtonBehaviourNode"))
        self.verticalLayout_2.addWidget(self.radioButtonBehaviourNode)
        self.radioButtonBehaviourArc = QtGui.QRadioButton(self.layoutWidget6)
        self.radioButtonBehaviourArc.setObjectName(_fromUtf8("radioButtonBehaviourArc"))
        self.verticalLayout_2.addWidget(self.radioButtonBehaviourArc)
        self.listViewBehaviour = QtGui.QListWidget(self.tab_behaviour)
        self.listViewBehaviour.setGeometry(QtCore.QRect(150, 60, 191, 192))
        self.listViewBehaviour.setObjectName(_fromUtf8("listViewBehaviour"))
        self.groupBoxRules = QtGui.QGroupBox(self.tab_behaviour)
        self.groupBoxRules.setGeometry(QtCore.QRect(420, 40, 171, 80))
        self.groupBoxRules.setObjectName(_fromUtf8("groupBoxRules"))
        self.radioButtonHasPortVariables = QtGui.QRadioButton(self.groupBoxRules)
        self.radioButtonHasPortVariables.setGeometry(QtCore.QRect(0, 20, 151, 22))
        self.radioButtonHasPortVariables.setObjectName(_fromUtf8("radioButtonHasPortVariables"))
        self.tabWidget.addTab(self.tab_behaviour, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 301, 221))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.treeWidget = QtGui.QTreeWidget(self.groupBox)
        self.treeWidget.setGeometry(QtCore.QRect(20, 30, 256, 192))
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.treeWidget.header().setVisible(False)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 670, 801, 111))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.msgWindow = QtGui.QTextBrowser(self.groupBox_2)
        self.msgWindow.setEnabled(False)
        self.msgWindow.setGeometry(QtCore.QRect(10, 30, 781, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.msgWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.msgWindow.setFont(font)
        self.msgWindow.setAcceptDrops(False)
        self.msgWindow.setObjectName(_fromUtf8("msgWindow"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setOrientation(QtCore.Qt.Vertical)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Process Modeller", None))
        self.groupBoxNetwork.setTitle(_translate("MainWindow", "network", None))
        self.radioButtonIntra.setText(_translate("MainWindow", "intra", None))
        self.radioButtonInter.setText(_translate("MainWindow", "inter", None))
        self.pushAddChild.setText(_translate("MainWindow", "add child", None))
        self.pushRemoveChild.setText(_translate("MainWindow", "remove child", None))
        self.groupBoxFile.setTitle(_translate("MainWindow", "file", None))
        self.pushSave.setToolTip(_translate("MainWindow", "save ProMo base ontology", None))
        self.pushInfo.setToolTip(_translate("MainWindow", "information", None))
        self.pushGraph.setToolTip(_translate("MainWindow", "make ProMo ontology graph", None))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p>defines <span style=\" font-weight:600;\">structure</span> --&gt; bookkeeping </p><p><span style=\" font-weight:600;\">behaviour</span> --&gt; taxonometry of variabless</p></body></html>", None))
        self.groupBoxStructureComponents.setTitle(_translate("MainWindow", "components", None))
        self.radioButtonStructureNode.setText(_translate("MainWindow", "node", None))
        self.radioButtonStructureArc.setText(_translate("MainWindow", "arc", None))
        self.radioButtonStructureToken.setText(_translate("MainWindow", "token", None))
        self.listViewStructure.setToolTip(_translate("MainWindow", "<html><head/><body><p>click once to select</p><p>twice to jump to definition location</p></body></html>", None))
        self.listViewStructureExtension.setToolTip(_translate("MainWindow", "<html><head/><body><p>click once to select</p><p>twice to jump to definition location</p></body></html>", None))
        self.pushNewStructureElement.setToolTip(_translate("MainWindow", "add", None))
        self.pushDeleteStructureElement.setToolTip(_translate("MainWindow", "remove", None))
        self.pushNewStructureElementExtension.setToolTip(_translate("MainWindow", "add", None))
        self.pushDeleteStructureElementExtension.setToolTip(_translate("MainWindow", "remove", None))
        self.labelStructure.setText(_translate("MainWindow", "stucture", None))
        self.labelStructureExtension.setText(_translate("MainWindow", "extension", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_structure), _translate("MainWindow", "structure", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_structure), _translate("MainWindow", "<html><head/><body><p>structure the section that servest the bookkeeping. </p><p>Contains all items that appear in the models</p><p><span style=\" font-weight:600;\">nodes</span>: dynamics and distribution nature, </p><p><span style=\" font-weight:600;\">arcs</span> for each type of token the transport nature and the distribution nature, </p><p><span style=\" font-weight:600;\">tokens</span>: token item and refinement </p></body></html>", None))
        self.groupBoxBehaviourComponents.setTitle(_translate("MainWindow", "components", None))
        self.radioButtonBehaviourGraph.setText(_translate("MainWindow", "graph", None))
        self.radioButtonBehaviourNode.setText(_translate("MainWindow", "node", None))
        self.radioButtonBehaviourArc.setText(_translate("MainWindow", "arc", None))
        self.listViewBehaviour.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">single</span> click   --&gt; select</p><p><span style=\" font-weight:600;\">double</span> click --&gt; jump to where item has been defined</p></body></html>", None))
        self.groupBoxRules.setTitle(_translate("MainWindow", "rules", None))
        self.radioButtonHasPortVariables.setText(_translate("MainWindow", "has port variables", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_behaviour), _translate("MainWindow", "behaviour", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_behaviour), _translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">behaviour</span>: </p><p><span style=\" font-weight:600;\">graph</span> --&gt; network,</p><p><span style=\" font-weight:600;\">node</span> : constant, frame and state, </p><p><span style=\" font-weight:600;\">arc</span>: transport</p></body></html>", None))
        self.groupBox.setTitle(_translate("MainWindow", "Domain tree", None))
        self.treeWidget.setToolTip(_translate("MainWindow", "ProMo ontology domain tree", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Messages", None))

