# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assign_equations_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 705)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(100, 0))
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.ForceTabbedDocks|QtWidgets.QMainWindow.VerticalTabs)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 551, 661))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_node = QtWidgets.QWidget()
        self.tab_node.setObjectName("tab_node")
        self.frameNodeTop = QtWidgets.QFrame(self.tab_node)
        self.frameNodeTop.setGeometry(QtCore.QRect(20, 20, 511, 281))
        self.frameNodeTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameNodeTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameNodeTop.setObjectName("frameNodeTop")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frameNodeTop)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayoutNodeTop = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayoutNodeTop.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutNodeTop.setObjectName("verticalLayoutNodeTop")
        self.frameNodeBottom = QtWidgets.QFrame(self.tab_node)
        self.frameNodeBottom.setGeometry(QtCore.QRect(20, 330, 511, 281))
        self.frameNodeBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameNodeBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameNodeBottom.setObjectName("frameNodeBottom")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frameNodeBottom)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 491, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayoutNodeBottom = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayoutNodeBottom.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutNodeBottom.setObjectName("verticalLayoutNodeBottom")
        self.tabWidget.addTab(self.tab_node, "")
        self.tab_arc = QtWidgets.QWidget()
        self.tab_arc.setObjectName("tab_arc")
        self.frameArcTop = QtWidgets.QFrame(self.tab_arc)
        self.frameArcTop.setGeometry(QtCore.QRect(20, 20, 511, 281))
        self.frameArcTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameArcTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameArcTop.setObjectName("frameArcTop")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.frameArcTop)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(10, 10, 491, 261))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayoutArcTop = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayoutArcTop.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutArcTop.setObjectName("verticalLayoutArcTop")
        self.frameArcBottom = QtWidgets.QFrame(self.tab_arc)
        self.frameArcBottom.setGeometry(QtCore.QRect(20, 330, 511, 281))
        self.frameArcBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameArcBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameArcBottom.setObjectName("frameArcBottom")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frameArcBottom)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 491, 261))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayoutArcBottom = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayoutArcBottom.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutArcBottom.setObjectName("verticalLayoutArcBottom")
        self.tabWidget.addTab(self.tab_arc, "")
        self.tab_intraface = QtWidgets.QWidget()
        self.tab_intraface.setObjectName("tab_intraface")
        self.frameIntraTop = QtWidgets.QFrame(self.tab_intraface)
        self.frameIntraTop.setGeometry(QtCore.QRect(20, 20, 511, 281))
        self.frameIntraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameIntraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameIntraTop.setObjectName("frameIntraTop")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frameIntraTop)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 491, 261))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayoutIntraTop = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayoutIntraTop.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutIntraTop.setObjectName("verticalLayoutIntraTop")
        self.frameIntraBottom = QtWidgets.QFrame(self.tab_intraface)
        self.frameIntraBottom.setGeometry(QtCore.QRect(20, 330, 511, 281))
        self.frameIntraBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameIntraBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameIntraBottom.setObjectName("frameIntraBottom")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frameIntraBottom)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 491, 261))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayoutIntraBottom = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayoutIntraBottom.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutIntraBottom.setObjectName("verticalLayoutIntraBottom")
        self.tabWidget.addTab(self.tab_intraface, "")
        self.tab_interface = QtWidgets.QWidget()
        self.tab_interface.setObjectName("tab_interface")
        self.frameInterTop = QtWidgets.QFrame(self.tab_interface)
        self.frameInterTop.setGeometry(QtCore.QRect(20, 20, 511, 281))
        self.frameInterTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInterTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInterTop.setObjectName("frameInterTop")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.frameInterTop)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 491, 261))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayoutInterTop = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayoutInterTop.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutInterTop.setObjectName("verticalLayoutInterTop")
        self.frameInterBottom = QtWidgets.QFrame(self.tab_interface)
        self.frameInterBottom.setGeometry(QtCore.QRect(20, 330, 511, 281))
        self.frameInterBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInterBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInterBottom.setObjectName("frameInterBottom")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.frameInterBottom)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 491, 261))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayoutInterBottom = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayoutInterBottom.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutInterBottom.setObjectName("verticalLayoutInterBottom")
        self.tabWidget.addTab(self.tab_interface, "")
        self.pushNodeSave = QtWidgets.QPushButton(self.centralwidget)
        self.pushNodeSave.setGeometry(QtCore.QRect(640, 40, 101, 25))
        self.pushNodeSave.setObjectName("pushNodeSave")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setOrientation(QtCore.Qt.Vertical)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Process Modeller"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_node), _translate("MainWindow", "node"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_arc), _translate("MainWindow", "arc"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_intraface), _translate("MainWindow", "intraface"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_interface), _translate("MainWindow", "interface"))
        self.pushNodeSave.setText(_translate("MainWindow", "save"))
