# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_behaviour_linker_editor.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(683, 632)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 231, 112))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonDuplicates = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonDuplicates.setObjectName("radioButtonDuplicates")
        self.verticalLayout.addWidget(self.radioButtonDuplicates)
        self.radioButtonNewVariant = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonNewVariant.setObjectName("radioButtonNewVariant")
        self.verticalLayout.addWidget(self.radioButtonNewVariant)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButtonConstrain = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonConstrain.setObjectName("radioButtonConstrain")
        self.verticalLayout.addWidget(self.radioButtonConstrain)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.labelLeft = QtWidgets.QLabel(self.centralwidget)
        self.labelLeft.setObjectName("labelLeft")
        self.verticalLayout_2.addWidget(self.labelLeft)
        self.scrollAreaLeft = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaLeft.setWidgetResizable(True)
        self.scrollAreaLeft.setObjectName("scrollAreaLeft")
        self.scrollAreaWidgetContentsLeft = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsLeft.setGeometry(QtCore.QRect(0, 0, 247, 409))
        self.scrollAreaWidgetContentsLeft.setObjectName("scrollAreaWidgetContentsLeft")
        self.scrollAreaLeft.setWidget(self.scrollAreaWidgetContentsLeft)
        self.verticalLayout_2.addWidget(self.scrollAreaLeft)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayoutFirstColumn = QtWidgets.QVBoxLayout()
        self.verticalLayoutFirstColumn.setObjectName("verticalLayoutFirstColumn")
        self.scrollAreaInterNetworks = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaInterNetworks.setWidgetResizable(True)
        self.scrollAreaInterNetworks.setObjectName("scrollAreaInterNetworks")
        self.scrollAreaWidgetContentsInterNetworks = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsInterNetworks.setGeometry(QtCore.QRect(0, 0, 147, 191))
        self.scrollAreaWidgetContentsInterNetworks.setObjectName("scrollAreaWidgetContentsInterNetworks")
        self.scrollAreaInterNetworks.setWidget(self.scrollAreaWidgetContentsInterNetworks)
        self.verticalLayoutFirstColumn.addWidget(self.scrollAreaInterNetworks)
        self.scrollAreaEntities = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaEntities.setWidgetResizable(True)
        self.scrollAreaEntities.setObjectName("scrollAreaEntities")
        self.scrollAreaWidgetContentsEntities = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsEntities.setGeometry(QtCore.QRect(0, 0, 147, 190))
        self.scrollAreaWidgetContentsEntities.setObjectName("scrollAreaWidgetContentsEntities")
        self.scrollAreaEntities.setWidget(self.scrollAreaWidgetContentsEntities)
        self.verticalLayoutFirstColumn.addWidget(self.scrollAreaEntities)
        self.scrollAreaVariant = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaVariant.setWidgetResizable(True)
        self.scrollAreaVariant.setObjectName("scrollAreaVariant")
        self.scrollAreaWidgetContentsVariants = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsVariants.setGeometry(QtCore.QRect(0, 0, 147, 191))
        self.scrollAreaWidgetContentsVariants.setObjectName("scrollAreaWidgetContentsVariants")
        self.scrollAreaVariant.setWidget(self.scrollAreaWidgetContentsVariants)
        self.verticalLayoutFirstColumn.addWidget(self.scrollAreaVariant)
        self.gridLayout.addLayout(self.verticalLayoutFirstColumn, 0, 0, 1, 1)
        self.verticalLayoutThirdColumn = QtWidgets.QVBoxLayout()
        self.verticalLayoutThirdColumn.setObjectName("verticalLayoutThirdColumn")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 30, 164, 115))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonInformation = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonInformation.setText("")
        self.pushButtonInformation.setObjectName("pushButtonInformation")
        self.gridLayout_2.addWidget(self.pushButtonInformation, 1, 0, 1, 1)
        self.pushButtonCancle = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonCancle.setText("")
        self.pushButtonCancle.setObjectName("pushButtonCancle")
        self.gridLayout_2.addWidget(self.pushButtonCancle, 1, 4, 1, 1)
        self.pushButtonSave = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonSave.setText("")
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.gridLayout_2.addWidget(self.pushButtonSave, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        self.verticalLayoutThirdColumn.addWidget(self.groupBox_2)
        self.labelRight = QtWidgets.QLabel(self.centralwidget)
        self.labelRight.setObjectName("labelRight")
        self.verticalLayoutThirdColumn.addWidget(self.labelRight)
        self.scrollAreaRight = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaRight.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollAreaRight.setWidgetResizable(True)
        self.scrollAreaRight.setObjectName("scrollAreaRight")
        self.scrollAreaWidgetContentsRight = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsRight.setGeometry(QtCore.QRect(0, 0, 247, 409))
        self.scrollAreaWidgetContentsRight.setObjectName("scrollAreaWidgetContentsRight")
        self.scrollAreaRight.setWidget(self.scrollAreaWidgetContentsRight)
        self.verticalLayoutThirdColumn.addWidget(self.scrollAreaRight)
        self.gridLayout.addLayout(self.verticalLayoutThirdColumn, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 30)
        self.gridLayout.setColumnStretch(1, 50)
        self.gridLayout.setColumnStretch(2, 50)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "controls"))
        self.radioButtonDuplicates.setText(_translate("MainWindow", "duplicates"))
        self.radioButtonNewVariant.setText(_translate("MainWindow", "new variant"))
        self.radioButton.setText(_translate("MainWindow", "edit variant"))
        self.radioButtonConstrain.setText(_translate("MainWindow", "instantiate variant"))
        self.labelLeft.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.labelRight.setText(_translate("MainWindow", "TextLabel"))
